server:
  port: 9001 #order 9001 cart 9002 stock 9003
spring:
  cloud:
    nacos:
      discovery:
        #提供nacos注册中心地址
        server-addr: localhost:8848
  application:
    # 微服务中 表示的是 服务名称 nacos客户端会使用这个值
    name: luban-demo-order #拆分的项目应用名称 也不同
  profiles:
    active: local
