server:
  port: 9001 #order 9001 cart 9002 stock 9003
spring:
  cloud:
    nacos:
      discovery:
        #提供nacos注册中心地址
        server-addr: localhost:8848
        #实例的ip地址 多个网卡必定要配置 不配置
        ip: 127.0.0.1
        #配置实例端口好 默认就是server.port
        port: ${server.port}
        #配置当前实例启动注册的命名空间的id值
        namespace: dev
        #配置分组的值 默认 DEFAULT_GROUP
        group: 0.0.1-SNAPSHOT
        #指定当前实例的服务名称
        service: ${spring.application.name}
  application:
    # 微服务中 表示的是 服务名称 nacos客户端会使用这个值
    name: luban-demo-order #拆分的项目应用名称 也不同
  profiles:
    active: local
