GET http://localhost:10000/stock/hello?name=hexiaoluo&token=1234567890
###

GET http://localhost:10000/stock/hello?name=hexiaoluo
Authorization: 1234567890
###
GET http://localhost:10000/stock/hello?name=hexiaoluo
Cookie: token=1234567890